### ISSUE TITLE
Execution fails, but record gets created 

### ISSUE THREAD

**Issue by tboerger** [andrexus/terraform-provider-inwx#3]
The DNS record gets created within INWX, but it's not possible to execute terraform successfully... I tried to find the issue within the code without luck.

```
# terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + inwx_record.master
      id:     <computed>
      domain: "example.com"
      name:   "foobar"
      ttl:    "600"
      type:   "A"
      value:  "127.0.0.1"


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

inwx_record.master: Creating...
  domain: "" => "example.com"
  name:   "" => "foobar"
  ttl:    "" => "600"
  type:   "" => "A"
  value:  "" => "127.0.0.1"

Error: Error applying plan:

1 error(s) occurred:

* inwx_record.master: 1 error(s) occurred:

* inwx_record.master: 3 error(s) decoding:

* 'record[0].Prio' expected type 'int', got unconvertible type 'string'
* 'record[1].Prio' expected type 'int', got unconvertible type 'string'
* 'record[2].Prio' expected type 'int', got unconvertible type 'string'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by andrexus** [comment]
ttl parameter should be of type int. If you remove quotes from ttl (600 instead of "600") it should work fine

**Comment by tboerger** [comment]
I'm not quoting the TTL, this gets created like that by Terraform. So this provider is still not usable :(

**Comment by tboerger** [comment]
I will create a fork and try to pin down the issue.

**Comment by oliver1980** [comment]
I'm seeing this, too :(
Is this the API returning "Prio" as string, instead of Int?

**Comment by tboerger** [comment]
I haven't checked anything anymore. I went away from inwx Nameservers to cloudflare.

**Comment by derBroBro** [comment]
@andrexus are you still maintaining the project ? Dont see any sign since several months... 😞

**Comment by andrexus** [comment]
I’m already not using inwx for a long time. So you can consider this project as not maintained. But I will merge all contributed bug fixes

**Comment by derBroBro** [comment]
Great to hear from you! 😄 
We will see if we can create a PR for this. 
Best Greetings from Stuttgart! 
Malte

**Comment by tboerger** [comment]
I'm not using inwx anymore, so closing my issue.
